package com.semantalytics.stardog.kibble.jdbc;

import com.stardog.stark.IRI;
import com.stardog.stark.Values;

public enum JdbcVocabulary {

    allTablesAreSelectable,
    attributes,
    autoCommitFailureClosesAllResultSets,
    bestRowIdentifier,
    catalogs,
    catalogSeparator,
    catalogTerm,
    clientIntoProperties,
    columnPrivileges,
    columns,
    crossReference,
    databaseMajorVersion,
    databaseMinorVersion,
    databaseProductName,
    databaseProductVersion,
    dataDefinitionCausesTransactionCommit,
    dataDefinitionIgnoredInTransaction,
    dataDefinitionIgnoredInTransactions,
    defaultTransactionIsolation,
    deletesAreDetected,
    doesMaxRowSizeIncludeBlobs,
    driverAccepts,
    driverMajorVersion,
    driverMinorVersion,
    driverPropertyInfo,
    drivers,
    exportedKeys,
    extraNameCharacters,
    functionColumns,
    functions,
    generatedKeyAlwaysReturned,
    identifierQuoteString,
    importedKeys,
    indexInfo,
    insertsAreDetected,
    isCatalogAtStart,
    isDriverJdbcCompliant,
    isDriverRegistered,
    isReadOnly,
    locatorsUpdateCopy,
    maxBinaryLiteralLength,
    maxCatalogNameLength,
    maxCharLiteralLength,
    maxColumnNameLength,
    maxColumnsInGroupBy,
    maxColumnsInIndex,
    maxColumnsInOrderBy,
    maxColumnsInSelect,
    maxColumnsInTable,
    maxConnections,
    maxCursorNameLength,
    maxIndexLength,
    maxLogicalLobSize,
    maxProcedureNameLength,
    maxRowSize,
    maxSchemaNameLength,
    maxStatementLength,
    maxStatements,
    maxTableNameLength,
    maxTablesInSelect,
    maxUserNameLength,
    nullPlusNonNullIsNull,
    nullsAreSortedAtEnd,
    nullsAreSortedAtStart,
    nullsAreStortedHigh,
    nullsAreSortedLow,
    numericFunctions,
    othersDeletesAreVisible,
    othersInsertsAreVisible,
    othersUpdatesAreVisible,
    ownDeletesAreVisible,
    ownInsertsAreVisible,
    ownUpdatesAreVisible,
    primaryKeys,
    procedureColumns,
    procedures,
    procedureTerm,
    pseudoColumns,
    resultSetHoldability,
    rowIdLifetime,
    schemas,
    schemaTerm,
    searchStringEscape,
    sqlKeywords,
    sqlStateType,
    storesLowerCaseQuotedIdentifiers,
    storesMixedCaseQuotedIdentifiers,
    storesUpperCaseQuotedIdentifiers,
    stringFunctions,
    superTables,
    superTypes,
    supportsAlterTableWithAddColumn,
    supportsAlterTableWithDropColumn,
    supportsAnsi92EntryLevelSql,
    supportsAnsi92FullSql,
    supportsAnsi92IntermediateSql,
    supportsBatchUpdates,
    supportsCatalogsInDataManipulation,
    supportsCatalogsInIndexDefinitions,
    supportsCatalogsInPrivilegeDefinitions,
    supportsCatalogsInProcedureCalls,
    supportsCatalogsInTableDefinitions,
    supportsColumnAliasing,
    supportsConvert,
    supportsCoreSqlGrammar,
    supportsCorrelatedSubqueries,
    supportsDataDefinitionAndDataManipulationTransactions,
    supportsDataManipulationTransactionsOnly,
    supportsDifferentTableCorrelationNames,
    supportsExpressionsInOrderBy,
    SupportsExtendedSqlGrammar,
    supportsFullOuterJoins,
    supportsGetGeneratedKeys,
    supportsGroupBy,
    supportsGroupByBeyondSelect,
    supportsGroupByUnrelated,
    supportsIntegrityEnhancementFacility,
    supportsLikeEscapeClause,
    supportsLimitedOuterJoins,
    supportsMinimumSqlGrammar,
    supportsMixedCaseIdentifiers,
    supportsMultipleOpenResults,
    supportsMultipleTransactions,
    suportsNamedParameters,
    supportsNonNullableColumns,
    supportsOpenCursorsAcrossCommit,
    supportsopenCursorsAcrossRollback,
    supportsOpenStatementsAcrossCommit,
    supportsOpenStatementsAcrossRollback,
    supportsOrderByUnrelated,
    supportsOuterJoins,
    supprotspositionedDelete,
    supportsPositionedUpdte,
    supportsRefCursors,
    supportsResultSetConcurrency,
    supportsResultSetHoldability,
    supportsResultSetType,
    supportsSavePoints,
    supportsSchemasInDataManipulation,
    supportsSchemasInIndexDefinitions,
    supportsSchemasInPrivilegeDefinitions,
    supportsSchemasInProcedureCalls,
    supportsSchemasInTableDefinitions,
    supportsSelectForUpdate,
    supportsStatementPooling,
    supportsStoredFunctionsUsingCallSyntax,
    supportsStoredProcedures,
    supportsSubqueriesInComparisons,
    supportsSubqueriesInExists,
    supportsSubqueriesInIns,
    supportsSubqueriesInQuantifieds,
    supportsTableCorrelationNames,
    supportsTransactionIsolationLevel,
    supportsTransactions,
    supportsUnion,
    supportsUnionAll,
    systemFunctions,
    tablePrivileges,
    tables,
    tableTypes,
    timeDateFunctions,
    typeInfo,
    udts,
    updatesAreDetected,
    usesLocalFiles,
    usesLocalFilesPerTable,
    versionColumns;

    public static final String NAMESPACE = "http://semantalytics.com/2017/09/ns/stardog/kibble/jdbc/";
    public final IRI iri;

    JdbcVocabulary() {
        iri = Values.iri(NAMESPACE, name());
    }

    public static String sparqlPrefix(String prefixName) {
        return "PREFIX " + prefixName + ": <" + NAMESPACE + "> ";
    }

    public String stringValue() {
        return iri.toString();
    }
}
